import Footer from "@/components/Footer";
import Header from "../components/Header";

import { Lato, Playfair_Display } from "next/font/google";

import "./global.css";

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "300", "400", "700", "900"],
  variable: "--lato",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700", "900"],
  variable: "--playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${lato.variable} ${playfair.variable}`} lang="en" >
      <body className="text-secondary bg-primary fs-400 ff-body">
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html >
  );
}
